# Generated by Django 4.2.7 on 2025-05-09 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('mtn', 'MTN Mobile Money'), ('airtel', 'Airtel Money')], max_length=10, verbose_name='Payment Method')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='Transaction ID')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Paid')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('network', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Network')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Payment Status')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail', to='marketplace.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
