# Generated by Django 4.2.7 on 2025-05-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_receiptlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptlog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receiptlog',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
