# Generated by Django 5.2 on 2025-05-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_orderitem_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('payment_on_delivery', 'Payment on Delivery'), ('mtn_money', 'MTN Mobile Money'), ('airtel_money', 'Airtel Money')], default='cash', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
