# Generated by Django 4.2.7 on 2025-05-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_rating_options_rating_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
