# Generated by Django 4.2.7 on 2025-05-14 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_alter_chatroom_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='marketplace.product'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('buyer', 'seller', 'product')},
        ),
    ]
